server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: #18761为双中心状态增加
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # http://localhost:8761/eureka/,http://localhost:18761/eureka/
